GID Flag and Node.Self Structure
pokt-network/pocket-core pull request #117
Opened 2019-01-10 20:00 UTC by andrewnguyen22

Added flag: --gid "myGID"
Added node.Self singleton structure for easy self node properties like GID ^

2019-01-14 23:54 UTC, iajrz requested changes
[rpc.RunAPIEndpoints](https://github.com/pokt-network/pocket-core/pull/117/files#diff-1318addeee65b25b7124bace036f67d9R63) seems not to be available in this change set. Maybe there was a mixup when staging. This branch can't be built. 
[`ExitGracefully`](https://github.com/pokt-network/pocket-core/pull/117/files#diff-8a1278a5855334feb584493def4bfec5R8) should log the cause for exiting, not just print it.
I expected, because of the issue, that the default GID would be "dummyGID". 0 works too; if this was ignored on purpose, all is well.

2019-01-15 15:37 UTC, andrewnguyen22 commented
Ahh yes, the manual merging is what did me in! Good catch, I fixed and made the changes you requested!

2019-01-15 19:26 UTC, iajrz commented
9e37f20 created an import cycle which prevented the project from building. I eliminated it in d125d79.

2019-01-15 19:27 UTC, iajrz submitted a review, later dismissed

2019-01-15 19:47 UTC, merged