reduce memory footprint for blocktxs & accounttxs
pokt-network/pocket-core pull request #1179
Opened 2020-11-03 20:45 UTC by edjroz

Close #1090 
- [ ] Add ordering for paging (default "desc")
- [ ] Update tendermint to consume less memory when querying

2020-11-09 13:34 UTC, oten91 submitted a review, later dismissed

2020-11-09 16:43 UTC, andrewnguyen22 requested changes, later dismissed

2020-11-09 16:43 UTC, andrewnguyen22 commented on app/cmd/rpc/query.go
> +		Txs:        make([]*RPCResultTx, 0, len(res.Txs)),
```suggestion
		Txs:        make([]*RPCResultTx, 0, res.TotalCount),
```

2020-11-09 16:43 UTC, andrewnguyen22 commented on go.mod
> +	github.com/tendermint/tendermint v0.33.8
```suggestion
	github.com/tendermint/tendermint v0.33.7
```

2020-11-10 13:58 UTC, oten91 approved these changes, later dismissed

2020-11-10 14:00 UTC, oten91 approved these changes, later dismissed

2020-11-10 14:59 UTC, oten91 submitted a review, later dismissed

2020-11-10 15:05 UTC, andrewnguyen22 submitted a review, later dismissed

2020-11-10 15:09 UTC, oten91 approved these changes, later dismissed

2020-11-10 15:36 UTC, oten91 approved these changes

2020-11-10 15:48 UTC, merged