Unconfirmed txs
pokt-network/pocket-core pull request #1460
Opened 2022-07-21 22:16 UTC by jorgecuesta

- Added /v1/query/unconfirmed_txs
    - returns unconfirmed transactions following blocktxs params (page & per_page) and blocktxs response
    - txs are decoded following same blocktxs format (hash + stdTx)
- Added /v1/query/unconfirmed_tx
    - look by hash on tendermint unconfirmed_txs and return it following blocktxs params and response
- Added Test for Query and RPC

2022-07-22 14:29 UTC, jorgecuesta commented
/v1/query/unconfirmed_tx sample
```bash
curl -X POST localhost:8081/v1/query/unconfirmed_tx -d '{"hash":"E6D01A59E4E39DD43C118281AA19328B211949A72CC6B95A3927A43B91A0583A"}'
```
```json
{
  "hash": "E6D01A59E4E39DD43C118281AA19328B211949A72CC6B95A3927A43B91A0583A",
  "stdTx": {
    "entropy": -1916588616508533000,
    "fee": [
      {
        "amount": "10000",
        "denom": "upokt"
      }
    ],
    "memo": "C0D3R offline wallet TEST transfer",
    "msg": {
      "type": "pos/Send",
      "value": {
        "amount": "1000000",
        "from_address": "3792d1a2d7281a3e4a678961f9e766cd845a8a6f",
        "to_address": "02853572f0b76c5af347f824b11a0262efe85082"
      }
    },
    "signature": {
      "pub_key": "b99c39324d0bb9cda51908d17e10e71267fb69337f0a3c5e89ef92324bf789a0",
      "signature": "6dfa3fa0baa01822dc1908662e89d42cb7600104340ea44bfae88ab77d23be32c751967d3aec5bb1bbea1c6b65f16ec302e60f87becc4111ecfc7023474f370a"
    }
  }
}
```

2022-07-22 14:30 UTC, jorgecuesta commented
/v1/query/unconfirmed_txs
```bash
curl -X POST localhost:8081/v1/query/unconfirmed_txs -d '{"page": 1, "per_page": 5}'
```
```json
{
  "page_count": 5,
  "total_txs": 3272,
  "txs": [
    {
      "hash": "E6D01A59E4E39DD43C118281AA19328B211949A72CC6B95A3927A43B91A0583A",
      "stdTx": {
        "entropy": -1916588616508533000,
        "fee": [
          {
            "amount": "10000",
            "denom": "upokt"
          }
        ],
        "memo": "C0D3R offline wallet TEST transfer",
        "msg": {
          "type": "pos/Send",
          "value": {
            "amount": "1000000",
            "from_address": "3792d1a2d7281a3e4a678961f9e766cd845a8a6f",
            "to_address": "02853572f0b76c5af347f824b11a0262efe85082"
          }
        },
        "signature": {
          "pub_key": "b99c39324d0bb9cda51908d17e10e71267fb69337f0a3c5e89ef92324bf789a0",
          "signature": "6dfa3fa0baa01822dc1908662e89d42cb7600104340ea44bfae88ab77d23be32c751967d3aec5bb1bbea1c6b65f16ec302e60f87becc4111ecfc7023474f370a"
        }
      }
    },
    {
      "hash": "33FA936809C810602E658024437AC920EA26F5CD1CD79373EA1A4607783B9180",
      "stdTx": {
        "entropy": 6154625557175978000,
        "fee": [
          {
            "amount": "10000",
            "denom": "upokt"
          }
        ],
        "memo": "",
        "msg": {
          "type": "pocketcore/claim",
          "value": {
            "evidence_type": "1",
            "expiration_height": "0",
            "from_address": "0ffce91a58421b8026c2b77daf4f4097aeb6690d",
            "header": {
              "app_public_key": "8b76c64bc8dc854ddbc472bd9932d2b0193c4291c7b50c1ee05af1ba5fd8e56c",
              "chain": "0004",
              "session_height": "65821"
            },
            "merkle_root": {
              "merkleHash": "oGbAuySzBuijWGZ5mU62PD1zJL/qdt6NRw+mcU3b4LM=",
              "range": {
                "lower": "0",
                "upper": "18446605143783198979"
              }
            },
            "total_proofs": "29726"
          }
        },
        "signature": {
          "pub_key": "a0a7acc447db56fe5dfe7b6a520c7b6703f8ac5587793bed82b1850e272385f5",
          "signature": "d606b0f464e86640a6e999cdf80c176336dc14e5bff652ee3d7ee27e48585228aed8b10f5a06d6c79d75a634b2588b51cf0c1fb485bb467760eaf82c34ba6a0a"
        }
      }
    },
    {
      "hash": "E69B8ACA09D1A1DD52466EF0168BCED9A74BE002C40C0EA04D97A4BF33E2456C",
      "stdTx": {
        "entropy": 180836423741798000,
        "fee": [
          {
            "amount": "10000",
            "denom": "upokt"
          }
        ],
        "memo": "C0D3R offline wallet TEST transfer",
        "msg": {
          "type": "pos/Send",
          "value": {
            "amount": "1000000",
            "from_address": "47dcafddf8918f44ff1f3724415691fd1f54af27",
            "to_address": "d9ceb78e3df747d72f7f5e2e58c63a47e35fed4f"
          }
        },
        "signature": {
          "pub_key": "75e0c4ef1d18201da2fcaf8902daa56f6adfca6f594cb2afea2c2607d867da10",
          "signature": "4bbbe61d43de608ebd2de5cb1e67bb8cf9e94d94774cd1a65aa45630ef9966d672755c8efe8e7b2df152cd5e9545a37a563d2cf9d4929bae173546c0d8bec209"
        }
      }
    },
    {
      "hash": "DD01F07961C2AE98009B25B0D985F4C75942DC7B41F3F51BC1E2F593A41C0DD2",
      "stdTx": {
        "entropy": 434636169534067000,
        "fee": [
          {
            "amount": "10000",
            "denom": "upokt"
          }
        ],
        "memo": "C0D3R offline wallet TEST transfer",
        "msg": {
          "type": "pos/Send",
          "value": {
            "amount": "1000000",
            "from_address": "73cc8a3a3e00bef143c3cd0d9a110fa7ffc89958",
            "to_address": "1a0bf19168a660e3cc3ee3f2bea2890b63834850"
          }
        },
        "signature": {
          "pub_key": "f8cf56f97dc00769a3920cbaee8ca9fddd854f3394b218c52329f5410662448b",
          "signature": "6ac23fe58ac2ace3bb3a61f83a584580922342f87b9a6163257189282877e10d6516367789e79863c124228dfc63bedc1f5c93e4c7473243f011549d69415405"
        }
      }
    },
    {
      "hash": "E1EC6B190D8DD6DB3C0A8F4C4F94C57937DFE55A55ACD281D980A284E03BC079",
      "stdTx": {
        "entropy": 1633855065885397500,
        "fee": [
          {
            "amount": "10000",
            "denom": "upokt"
          }
        ],
        "memo": "",
        "msg": {
          "type": "pocketcore/claim",
          "value": {
            "evidence_type": "1",
            "expiration_height": "0",
            "from_address": "63b2f6bbd9d98dd84d26eaf26afe5ef765c2c4cb",
            "header": {
              "app_public_key": "6ddb3b52bbedd4c0a908816dacc1ca70cf0b52f2480691c4981ae47e2827aacc",
              "chain": "0040",
              "session_height": "65821"
            },
            "merkle_root": {
              "merkleHash": "cwIrNDHlDIUw+ppiL+GubuGJNZtadMresFxIPwwMBeg=",
              "range": {
                "lower": "0",
                "upper": "18443614040906837944"
              }
            },
            "total_proofs": "13453"
          }
        },
        "signature": {
          "pub_key": "00a0102a07c381319f813df2cd05038e1b7d3749aaf6ac79e5c8f9a088a6217a",
          "signature": "12c54ddf0e0e99a9ec3a600c36a251f2651b1bfa5543c0a12adf1f390724c00d2be90f35b8c08b2f22110263de3432df42eba30cd5062a811740cd993f5b6609"
        }
      }
    }
  ]
}
```

2022-08-11 16:11 UTC, oten91 commented
@jorgecuesta Please rebase

2022-08-11 21:13 UTC, luyzdeleon approved these changes
This PR adheres to the proposal issue and code seems to be functional according to unit testing.

2022-08-15 15:59 UTC, oten91 requested changes
Looks good, Please Fix the minor issues on rpc-spec.yaml.

2022-08-15 15:59 UTC, oten91 commented on doc/specs/rpc-spec.yaml
> +=======
Fix Remains from rebase / merge

2022-08-15 15:59 UTC, oten91 commented on doc/specs/rpc-spec.yaml
> +>>>>>>> 827b76bc (Added RPC Spec about unconfirmedtxs and unconfirmedtx endpoints.)
Fix Remains from rebase / merge

2022-08-15 15:59 UTC, oten91 commented on doc/specs/rpc-spec.yaml
> +<<<<<<< HEAD
Fix Remains from rebase / merge

2022-08-22 17:48 UTC, oten91 approved these changes

2022-08-22 17:48 UTC, merged