Fix TestValidatorStateChange_EditAndValidateStakeValidator
pokt-network/pocket-core pull request #1533
Opened 2023-03-12 21:47 UTC by msmania

The test `TestValidatorStateChange_EditAndValidateStakeValidator` failed because `got.OutputAddress` was `nil` but `tt.want.OutputAddress` had a valid address.  Since this test is to test the behavior before NCUST, we make sure the fetched output address is nil and the rest of fields are the same as `tt.want`.

The behavior after NCUST is tested through the test `TestValidatorStateChange_EditAndValidateStakeValidatorAfterNonCustodialUpgrade`, which passes without failures.

2023-03-29 01:50 UTC, Olshansk requested changes

2023-03-29 01:50 UTC, Olshansk commented on x/nodes/keeper/valStateChanges_test.go
> +			got.OutputAddress = tt.want.OutputAddress
```suggestion
                         // Manually updated `got` to account for post NCUST updates
			got.OutputAddress = tt.want.OutputAddress
```

2023-03-29 22:01 UTC, msmania commented on x/nodes/keeper/valStateChanges_test.go
> +			got.OutputAddress = tt.want.OutputAddress
Added.

2023-04-04 22:30 UTC, Olshansk approved these changes

2023-04-06 22:19 UTC, merged