[WIP] LocalNet documentation
pokt-network/pocket-core pull request #1535
Opened 2023-03-15 17:06 UTC by Olshansk

2023-03-16 03:24 UTC, Olshansk commented
@msmania Check out the video. This is the work I was telling you about a couple days ago.

2023-03-29 02:16 UTC, Olshansk commented
@PoktBlade @msmania Can you guys give the LocalNet documentation a shot when you have a chance? 

You might need to use [this tendermint branch](https://github.com/pokt-network/tendermint/pull/71).

Note the following.

**The goals of this are to:**
    - Gain confidence into the changes being introduced
    - Create some ability to develop locally

**The non-goals are to:**
    - Invest in a great developer experience
    - Build long-lasting infrastructure & tool

2023-04-04 17:36 UTC, msmania commented on localnet.md
> +git clone git@github.com:pokt-network/pocket-e2e-stack.git
We can add `--recursive` option so that we don't have to run `git submodule` separately.

2023-04-04 17:37 UTC, msmania commented on localnet.md
> +### Verify Directory Structure
What this section verifies is too obvious.  Let's cut.

2023-04-04 17:41 UTC, Olshansk commented
/reviewpad summarize

2023-04-04 17:47 UTC, msmania commented on localnet.md
> +2. Update `POCKET_CORE_REPOS_PATH` in `.playground.env` to be the full path reflecting the path where you downloaded all the repos
It's easier to update `POCKET_CORE_REPOS_PATH` with `sed`.

```
sed -i 's|^POCKET_CORE_REPOS_PATH=.*$|POCKET_CORE_REPOS_PATH='$PWD'|' pocket-e2e-stack/.env
sed -i 's|^POCKET_CORE_REPOS_PATH=.*$|POCKET_CORE_REPOS_PATH='$PWD'|' pocket-e2e-stack/.playground.env
```

2023-04-04 17:47 UTC, msmania commented on localnet.md
> +3. Update `ETH_ALTRUIST` and `POLY_ALTRUIST` appropriately.
We can use `sed` here too.

```
sed -i 's|^# ETH_ALTRUIST=.*$|ETH_ALTRUIST=<Your or public Ethereum endpoint>|' pocket-e2e-stack/.env
sed -i 's|^# POLY_ALTRUIST=.*$|POLY_ALTRUIST=<Your or public Polygon endpoint>|' pocket-e2e-stack/.env
```

2023-04-04 17:54 UTC, msmania commented on localnet.md
> +watch -n 5 "curl -s -X 'POST' 'http://localhost:8084/v1/query/height'
A trailing double quote is missing.

2023-04-04 18:04 UTC, msmania commented on localnet.md
> +**IMPORTANT: Inspect the logs in case something looks abnormal or an error occurred.**
It will be helpful if we have a simple description about the stack like this.

This stack consists of four pocket validator nodes.  You can submit [a Pocket RPC](https://editor.swagger.io/?url=https://raw.githubusercontent.com/pokt-network/pocket-core/staging/doc/specs/rpc-spec.yaml) to each node via 8082, 8083, 8084, and 8085/tcp respectively, and a [Tendermint RPC](https://editor.swagger.io/?url=https://raw.githubusercontent.com/tendermint/tendermint/master/rpc/openapi/openapi.yaml) to each node via 26658, 26659, 26660, 26661/tcp respectively.

2023-04-04 18:09 UTC, msmania commented on localnet.md
> +# V0 LocalNet <!-- omit in toc -->
This file should be in doc/guides.

2023-04-04 18:10 UTC, msmania commented on x/pocketcore/types/merkle.go
> +
irrelevant change

2023-04-04 21:43 UTC, msmania commented
To make LocalNet work on WSL2, I made the following changes on dependent repos.  With these, I confirmed the LocalNet handles relays and processed claim and proof.

- https://github.com/pokt-network/pocket-e2e-stack/pull/1
- https://github.com/pokt-network/tx-bot/pull/7

2023-04-04 21:46 UTC, msmania requested changes
To make LocalNet work on WSL2, I made the following changes on dependent repos.  With these, I confirmed the LocalNet handled relays and processed claim and proof.

- https://github.com/pokt-network/pocket-e2e-stack/pull/1
- https://github.com/pokt-network/tx-bot/pull/7

2023-04-05 16:48 UTC, msmania commented
Thanks!  The document and video looks nice and clear.

2023-04-05 16:48 UTC, msmania approved these changes, later dismissed

2023-04-05 19:02 UTC, merged