Add msgstake_flow.md
pokt-network/pocket-core pull request #1544
Opened 2023-04-07 03:39 UTC by msmania

2023-04-10 23:08 UTC, Olshansk requested changes

2023-04-10 23:08 UTC, Olshansk commented on doc/specs/msgstake_flow.md
> +  A --> H(baseApp/runMsg)
`runMsg` only happens after we `validateTransaction`. 

I think:
1. Splitting it into two flowcharts would make it easier
2. Making the flowcharts `TD` instead o `LR`
3. In `(F[ok])`, making it `see runMsg`

2023-04-10 23:08 UTC, Olshansk commented on doc/specs/msgstake_flow.md
> +	B --> C{After the upgrade?}
In a second line, specify which upgrade

2023-04-10 23:08 UTC, Olshansk commented on doc/specs/msgstake_flow.md
> +  A --> H(baseApp/runMsg)
Don't be afraid to split into multiple smaller diagrams. It makes it easier to navigate, share and read.

For example, just scroll (no reason to dive into the details) of https://github.com/pokt-network/pocket/wiki/Utility-Relay-Protocol

2023-04-10 23:08 UTC, Olshansk commented on doc/specs/msgstake_flow.md
> +  J --> K{Aafter the upgrade?\nChanging the output address?\nSigned by the current output address?}
```suggestion
  J --> K{After the upgrade?\nChanging the output address?\nSigned by the current output address?}
```

2023-04-10 23:08 UTC, Olshansk commented on doc/specs/msgstake_flow.md
> +  K -- No --> M(x/nodes/keeper/ValidateValidatorMsgSigner\nwith the new state)
```suggestion
  K -- Any no --> M(x/nodes/keeper/ValidateValidatorMsgSigner\nwith the new state)
```

2023-04-10 23:08 UTC, Olshansk commented on doc/specs/msgstake_flow.md
> +  Z --> AA([Happy ending!])
![giphy](https://user-images.githubusercontent.com/1892194/231015811-245a2751-5ebf-467e-9aaf-3c4146912327.gif)

2023-04-10 23:08 UTC, Olshansk commented on doc/specs/msgstake_flow.md
> +  J --> K{Aafter the upgrade?\nChanging the output address?\nSigned by the current output address?}
<img width="797" alt="Screenshot 2023-04-10 at 4 07 38 PM" src="https://user-images.githubusercontent.com/1892194/231015910-26398c27-d36e-47ca-874f-7a161610c1f0.png">

It's kind of hard to understand the flow here and what's expected. 

Again, I think multiple small TD diagrams will help clarify it

2023-04-12 00:27 UTC, msmania commented on doc/specs/msgstake_flow.md
> +  J --> K{Aafter the upgrade?\nChanging the output address?\nSigned by the current output address?}
Okay, split into four charts and added simple descriptions in each section.

2023-04-12 00:38 UTC, Olshansk approved these changes
THIS IS SO GOOD!!! 🙏 🙏 🙏 🙏

2023-04-12 00:48 UTC, merged

2023-04-12 00:52 UTC, msmania commented
I feel this is an excessive effort, but yeah, it looks much better and hopefully this helps someone.  Thank you for your thorough review as always!