Add mainnet seeds to README
pokt-network/pocket-core pull request #1594
Opened 2024-01-19 23:45 UTC by Olshansk

## Description

reviewpad:summary

2024-01-20 01:11 UTC, StevenMartinez94 approved these changes, later dismissed

2024-01-20 01:14 UTC, msmania requested changes

2024-01-20 01:14 UTC, msmania commented on README.md
> +MainNet seeds are being maintained by [NodeFleet](https://nodefleet.org/) and more details can be found at [mainnet.md](./docs/guides/mainnet.md).
s/docs/doc/

2024-01-22 01:54 UTC, msmania requested changes

2024-01-22 01:54 UTC, msmania commented on README.md
> +MainNet seeds are being maintained by [NodeFleet](https://nodefleet.org/) and more details can be found at [mainnet.md](./doc/guides/mainnet.md).
Can you use  the link to https://github.com/pokt-network/pocket-seeds instead of a new file?

2024-01-22 01:54 UTC, msmania commented on README.md
> +MainNet seeds are being maintained by [NodeFleet](https://nodefleet.org/) and more details can be found at [mainnet.md](./doc/guides/mainnet.md).
I found a typo in "Accessing TestNet" above.  Can you include a fix for that too?
doc/guide/testnet.md --> doc/guides/testnet.md

2024-01-23 02:22 UTC, msmania approved these changes
Thanks!

2024-01-23 21:56 UTC, merged