Update the seeds information in README.md
pokt-network/pocket-core pull request #1609
Opened 2024-08-14 17:55 UTC by breezytm

## Description

Replaced maintainers from Nodefleet.org to Stakenodes.org

2024-08-14 18:19 UTC, Olshansk requested changes

2024-08-14 18:19 UTC, Olshansk commented on README.md
> +TestNet information can be found at [testnet.md](doc/guides/testnet.md) and is maintained by the [Stakenodes](https://stakenodes.org/) team.
Please update https://github.com/pokt-network/pocket-core/blob/staging/doc/guides/testnet.md as well

2024-08-14 18:41 UTC, breezytm commented on README.md
> +TestNet information can be found at [testnet.md](doc/guides/testnet.md) and is maintained by the [Stakenodes](https://stakenodes.org/) team.
I will. I am going through the contents to determine what is actually needed and those that can be removed. I never had a request for tendermint access; therefore, it is unclear to me if that is something I should be making accessible.

2024-08-15 23:14 UTC, Olshansk commented on README.md
> +TestNet information can be found at [testnet.md](doc/guides/testnet.md) and is maintained by the [Stakenodes](https://stakenodes.org/) team.
Yea, let's maintain parity with what the previous testnet maintainers had.

2024-10-10 13:57 UTC, closed without merging