added dep to project
pokt-network/pocket-core pull request #22
Opened 2018-11-09 06:10 UTC by andrewnguyen22

closes #16

2018-11-09 15:44 UTC, luyzdeleon commented on Gopkg.toml
> +# Gopkg.toml example
Remove example comments.

2018-11-09 15:45 UTC, luyzdeleon requested changes
Add vendor/ to gitignore, as every environment needs to build their own based on package management.

2018-11-12 15:18 UTC, andrewnguyen22 commented on Gopkg.toml
> +# Gopkg.toml example
Check it out now

2018-11-12 15:26 UTC, luyzdeleon approved these changes

2018-11-12 15:26 UTC, andrewnguyen22 commented on Gopkg.toml
> +# Gopkg.toml example
Removed .idea

2018-11-12 16:10 UTC, merged