Issue #11
pokt-network/pocket-core pull request #25
Opened 2018-11-13 17:56 UTC by luyzdeleon

Closes #10 and #11

2018-11-13 19:26 UTC, andrewnguyen22 requested changes
Changes for Developer Setup Guide:
1) This guide is for anyone ~~working on~~ contributing to the development and implementation of Pocket Core. This guide will evolve alongside the development of this project and will be ~~kept~~ updated if any major changes ~~that~~ affect this setup process.
2) You can always setup symlinks if you want to have control over your directory structure while developing ~~for~~ any GO project.
3)  This will be taken into consideration when performing Pull Request reviews, ~~and~~ **as** it will ~~be helpful to~~ save the Pocket Core Team review time if your code is already formatted to standard.

2018-11-13 19:26 UTC, andrewnguyen22 commented on README.md
> +The Pocket Core application will allow anyone to spin up a Pocket Network Full Node, with options to enable/disable functionality and modules according to each deployment. For more information on the
Change "Full Node" to "full node"

2018-11-13 19:26 UTC, andrewnguyen22 commented on README.md
> +- `--datadir <absolute path>` to configure the data directory where the blockchain information will be stored. The default value is: `/path/to/data/dir`.
Currently, the default value for --datadir isn't doing anything. Wondering if this is worth mentioning or not.

2018-11-13 19:26 UTC, andrewnguyen22 commented on README.md
> +Pocket Core is an open source project, and as such we welcome any contribution from anyone on the internet. Please read our [Developer Setup Guide](https://github.com/pokt-network/pocket-core/wiki/De
Remove redundant "for a guide"

2018-11-13 19:26 UTC, andrewnguyen22 commented on README.md
> +Reach us out in our [Slack](https://www.pokt.network/slack-pokt) and start a discussion with the Pocket Core Team regarding your change before you start working, communication is key for open source
Change "Reach us out in our [Slack]" to "Reach out to us on [Slack]"
Change "before you start working, communication is key" to "before you start working. Communication is key"

2018-11-13 19:57 UTC, luyzdeleon commented on README.md
> +- `--datadir <absolute path>` to configure the data directory where the blockchain information will be stored. The default value is: `/path/to/data/dir`.
If we're planning on changing the behaviour to mandatory input for that flag, then yeah we could delete it from here.

2018-11-13 20:02 UTC, luyzdeleon commented
Fixed errors on Development Setup Guide as well.

2018-11-14 14:16 UTC, andrewnguyen22 approved these changes

2018-11-14 14:28 UTC, merged