Issue #440
pokt-network/pocket-core pull request #443
Opened 2019-09-12 12:52 UTC by andrewnguyen22

Closes #440

2019-09-12 19:59 UTC, luyzdeleon requested changes

2019-09-12 19:59 UTC, luyzdeleon commented on tests/bdd/servicing/service_test.go
> +		Context("Invalid payload", func() {
I believe `payload` should be optional. Or maybe we should restructure the Relay data structure.

2019-09-12 19:59 UTC, luyzdeleon commented on tests/bdd/servicing/service_test.go
> +				Expect(validRelay.IsValid(hostedBlockchains)).To(BeNil())
`IsValid` should return a bool and an error. Or maybe be something like: `validRelay.validate(hostedBlockchains)` and that way returning just an `error` makes more sense.

2019-09-12 19:59 UTC, luyzdeleon commented on tests/bdd/servicing/service_test.go
> +	PDescribe("Relay execution", func() {})
Should we add a `PDescribe("Relay caching", func() {})` to include caching the work done?

2019-09-12 19:59 UTC, luyzdeleon commented on x/service/incrementCounter.go
> +func (ic IncrementCounter) IsValid(clientPubKey string, messageHash []byte) error {
Rename this to `Validate` so it makes more syntactical sense, or return both a bool and an error.

2019-09-12 19:59 UTC, luyzdeleon commented on x/service/relay.go
> +func (r Relay) IsValid(hostedBlockchains ServiceBlockchains) error {
Rename this to `Validate` so it makes more syntactical sense, or return both a bool and an error.

2019-09-12 19:59 UTC, luyzdeleon commented on x/service/relay.go
> +	result, err := executeHTTPRequest(r.Payload.Data.Bytes(), chainURL, r.Payload.Method)
I think this should be done according to a simplified interface that depending on what's contained on the `Relay` determines the network protocol to route this to.

2019-09-12 19:59 UTC, luyzdeleon commented on x/service/serviceToken.go
> +func (st ServiceToken) IsValid() error {
Same as above.

2019-09-12 19:59 UTC, luyzdeleon commented on x/service/serviceToken.go
> +func (st ServiceToken) VersionIsValid() error {
Same as above.

2019-09-12 19:59 UTC, luyzdeleon commented on x/service/serviceToken.go
> +func (st ServiceToken) MessageIsValid() error {
Same as above.

2019-09-12 19:59 UTC, luyzdeleon commented on x/service/serviceToken.go
> +func (st ServiceToken) SignatureIsValid() error {
Same as above.

2019-09-12 20:03 UTC, andrewnguyen22 commented on tests/bdd/servicing/service_test.go
> +		Context("Invalid payload", func() {
I don't think there is a situation where the payload would be optional

2019-09-12 20:04 UTC, andrewnguyen22 commented on tests/bdd/servicing/service_test.go
> +				Expect(validRelay.IsValid(hostedBlockchains)).To(BeNil())
Okay, that works with me!

2019-09-12 20:05 UTC, andrewnguyen22 commented on tests/bdd/servicing/service_test.go
> +	PDescribe("Relay execution", func() {})
I thought we were pushing `caching` to the infra level? If you are referring to relay batching then see PDescribe("Relay Batching")

2019-09-12 20:05 UTC, andrewnguyen22 commented on x/service/incrementCounter.go
> +func (ic IncrementCounter) IsValid(clientPubKey string, messageHash []byte) error {
Cool

2019-09-12 20:05 UTC, andrewnguyen22 commented on x/service/relay.go
> +func (r Relay) IsValid(hostedBlockchains ServiceBlockchains) error {
Cool

2019-09-12 20:06 UTC, andrewnguyen22 commented on x/service/relay.go
> +	result, err := executeHTTPRequest(r.Payload.Data.Bytes(), chainURL, r.Payload.Method)
Yes agreed, this is a placeholder

2019-09-12 20:06 UTC, andrewnguyen22 commented on x/service/serviceToken.go
> +func (st ServiceToken) IsValid() error {
Cool

2019-09-12 20:06 UTC, andrewnguyen22 commented on x/service/serviceToken.go
> +func (st ServiceToken) VersionIsValid() error {
Cool

2019-09-12 20:06 UTC, andrewnguyen22 commented on x/service/serviceToken.go
> +func (st ServiceToken) MessageIsValid() error {
Cool

2019-09-12 20:06 UTC, andrewnguyen22 commented on x/service/serviceToken.go
> +func (st ServiceToken) SignatureIsValid() error {
Cool

2019-09-13 12:51 UTC, luyzdeleon submitted a review, later dismissed

2019-09-13 13:05 UTC, luyzdeleon approved these changes

2019-09-13 13:05 UTC, merged