Issue #473
pokt-network/pocket-core pull request #474
Opened 2019-10-29 14:47 UTC by aqt01

Closes #473 #130 

![loglevel-example](https://user-images.githubusercontent.com/3402853/67778363-72f13100-fa39-11e9-990b-aa4076934e87.png)

2019-10-29 14:55 UTC, luyzdeleon requested changes

2019-10-29 14:55 UTC, luyzdeleon commented on tests/unit/log_test.go
> +	if err := logs.Log("Unit test for the json log functionality", logs.InfoLevel, logs.TextLogFormatter); err != nil {
There's a typo in text, it says: `Unit test for the json log functionality` when it should say: `Unit test for the text log functionality`

2019-10-29 14:55 UTC, luyzdeleon commented on tests/unit/log_test.go
> +	if err := logs.Log("Unit test for the trace log functionality", logs.TraceLevel, logs.JSONLogFormat); err != nil {
The text should indicate the log type as well as the level, e.g.: `Log type JSON Log level TRACE`

2019-10-29 14:55 UTC, luyzdeleon commented on tests/unit/log_test.go
> +	if err := logs.Log("Unit test for the trace log functionality", logs.TraceLevel, logs.TextLogFormatter); err != nil {
See above.

2019-10-29 14:55 UTC, luyzdeleon commented on tests/unit/log_test.go
> +func TestLoglevelFlag(t *testing.T) {
Should a test for when the incorrect log level is passed to the flag.

2019-10-31 15:51 UTC, andrewnguyen22 approved these changes

2019-10-31 15:52 UTC, merged