Issue #754
pokt-network/pocket-core pull request #766
Opened 2020-04-09 17:39 UTC by luyzdeleon

Closes #754

2020-04-09 23:32 UTC, andrewnguyen22 requested changes

2020-04-09 23:32 UTC, andrewnguyen22 commented on app/cmd/cli/query.go
> +			parsedPage, err := strconv.ParseInt(args[1], 10, 64)
Use strconv.Atoi() instead, no need to convert to int64

2020-04-09 23:32 UTC, andrewnguyen22 commented on app/cmd/cli/query.go
> +			parsedPage, err := strconv.ParseInt(args[1], 10, 64)
Do this for all parseInt()

2020-04-09 23:32 UTC, andrewnguyen22 commented on app/cmd/cli/query.go
> +		page := 1
These can be zero, because defaults are in query

2020-04-09 23:32 UTC, andrewnguyen22 commented on x/nodes/query.go
> +	if page > 0 {
These conditionals do not seem right

2020-04-09 23:32 UTC, andrewnguyen22 commented on x/nodes/query.go
> +	query := fmt.Sprintf("message.sender='%s'", addr)
Make this a constant

2020-04-09 23:32 UTC, andrewnguyen22 commented on x/nodes/query.go
> +	query := fmt.Sprintf("tx.height=%d", height)
Make this a constant

2020-04-10 03:05 UTC, luyzdeleon commented on app/cmd/cli/query.go
> +			parsedPage, err := strconv.ParseInt(args[1], 10, 64)
You're right for all, except the block height which needs to be an int64.

2020-04-10 03:05 UTC, luyzdeleon commented on app/cmd/cli/query.go
> +		page := 1
Correct!

2020-04-10 03:09 UTC, luyzdeleon commented on x/nodes/query.go
> +	if page > 0 {
The argument cannot be 0, as it causes the endpoint to error out. So as a nicety if you pass 0 it will use defaults.

2020-04-10 03:13 UTC, luyzdeleon commented on x/nodes/query.go
> +	query := fmt.Sprintf("message.sender='%s'", addr)
Applied not only to these, but also to other queries in the same file.

2020-04-10 03:13 UTC, luyzdeleon commented on x/nodes/query.go
> +	query := fmt.Sprintf("tx.height=%d", height)
Applied not only to these, but also to other queries in the same file.

2020-04-10 09:10 UTC, andrewnguyen22 commented
```
# github.com/pokt-network/pocket-core/app/cmd/cli
app/cmd/cli/query.go:90:7: no new variables on left side of :=
app/cmd/cli/query.go:91:10: no new variables on left side of :=
```

2020-04-10 14:37 UTC, andrewnguyen22 approved these changes

2020-04-10 16:02 UTC, merged