Add pagination
pokt-network/pocket-core pull request #774
Opened 2020-04-13 23:19 UTC by edjroz

Close #658 

Adds pagination to All possible applications & nodes queries on both RPC & CLI interfaces.

It will return pages in this standard
```
Result : []validators/applications
Page: int (current page)
Total: (total_amount_of_pages)
```

NOTE: @pokt-network/app-solutions Changes current structure for RPC calls.

2020-04-14 02:19 UTC, luyzdeleon requested changes
A couple things:
- Shouldn't the test emulate querying multiple pages? All queries seem to be fetching the first page on tests.
- Shouldn't the RPC specification and CLI documentations be updated?

2020-04-14 14:26 UTC, edjroz commented
> A couple things:
> 
> * Shouldn't the test emulate querying multiple pages? All queries seem to be fetching the first page on tests.
> * Shouldn't the RPC specification and CLI documentations be updated?

I'll get to work on those rn

2020-04-14 19:58 UTC, oten91 approved these changes

2020-04-15 17:50 UTC, luyzdeleon approved these changes

2020-04-15 18:21 UTC, merged