Issue #793
pokt-network/pocket-core pull request #808
Opened 2020-04-30 13:00 UTC by andrewnguyen22

closes #793 
closes #798 
closes #800 
closes #799

2020-04-30 13:43 UTC, luyzdeleon requested changes

2020-04-30 13:43 UTC, luyzdeleon commented on doc/changelog.md
> +- Added protocol level enforcement of service url `https`
@andrewnguyen22 Let's keep `http` available in the meantime to allow more time to the users to be able to provision SSL for their nodes in testnet.

2020-04-30 13:47 UTC, luyzdeleon commented
@andrewnguyen22 Genesis initialization needs validation to make sure `Network ID's` are the proper format, right now I can input any hash and it will be taken as valid. The 3 places where this needs to be checked is:

1. Pre-staked applications.
2.Pre-staked validators
3. Pocket Core supported blockchains.

2020-05-01 00:59 UTC, andrewnguyen22 commented
> @andrewnguyen22 Genesis initialization needs validation to make sure `Network ID's` are the proper format, right now I can input any hash and it will be taken as valid. The 3 places where this needs to be checked is:
> 
> 1. Pre-staked applications.
>    2.Pre-staked validators
> 2. Pocket Core supported blockchains.

Fixed

2020-05-01 15:48 UTC, luyzdeleon approved these changes

2020-05-01 15:51 UTC, merged