removed all panics from source code
pokt-network/pocket-core pull request #935
Opened 2020-05-11 21:40 UTC by andrewnguyen22

closes #869

2020-05-11 21:45 UTC, andrewnguyen22 commented
I know it's big, but please review carefully @edjroz @oten91 @luyzdeleon

2020-05-12 17:59 UTC, edjroz requested changes
Solid contribution however there is a missing panic, consider the suggestions however only the panic is necessary

2020-05-12 17:59 UTC, edjroz commented on app/cmd/rpc/server.go
> +		fmt.Println(err.Error())
should consider using log instead of fmt, log adds a timestamp to the message being printed.

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/proof.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("an error occured converting the relay challengeproof to bytes:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/proof.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("an error occured converting the relay RelayProof to bytesWithSignature:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/proof.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("an error occured converting the relay RelayProof to bytes:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/service.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("cannot marshal relay request hash: %s", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/service.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("an error occured converting the payload to bytes:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/service.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("an error occured hashing the relay response:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/session.go
> +	"os"
```suggestion
	"log"
```

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/session.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("an error occured converting the session header into bytes:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/service.go
> +	"os"
```suggestion
	"log"
```

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/proof.go
> +	"os"
```suggestion
	"log"
```

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/cache.go
> +	"os"
```suggestion
	"log"
```

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/cache.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("could not initialize cache storage: %s", err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/cache.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("can't unmarshal session iterator value into session: %s", err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/cache.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("can't unmarshal evidence iterator value into evidence: %s", err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/aat.go
> +	"os"
```suggestion
	"log"
```

2020-05-12 17:59 UTC, edjroz commented on x/pocketcore/types/aat.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("an error occured hashing the aat:\n%v", err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/nodes/types/valUtil.go
> +	"os"
```suggestion
	"log"
```

2020-05-12 17:59 UTC, edjroz commented on x/nodes/types/valUtil.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("cannot unmarshal validator with bytes: %s", hex.EncodeToString(valBytes))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/apps/keeper/keeper.go
> +	"os"
```suggestion
	"log"
```

2020-05-12 17:59 UTC, edjroz commented on x/apps/keeper/keeper.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("%s module account has not been set", types.StakedPoolName)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/apps/genesis.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("%s module account has not been set", types.StakedPoolName)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on x/apps/genesis.go
> +	"os"
```suggestion
	"log"
```

2020-05-12 17:59 UTC, edjroz commented on app/util.go
> +	"os"
```suggestion
	"log"
```

2020-05-12 17:59 UTC, edjroz commented on app/util.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("could not unmarshal json in SortJSON: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on app/util.go
> +		os.Exit(1)
```suggestion
  log.Fatalf("could not marshal back to json in SortJSON: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatalf("could not get home directory for data dir creation: %s",  err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatalf("cannot open config json file: %s",  err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
  log.Fatalf("cannot read config file: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
  log.Fatalf("cannot read config file into json: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
  log.Fatalf("canot open/create config json file: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
  log.Fatalf("cannot marshal default config into json: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
  log.Fatalf("cannot write default config to json file: %s",  err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +				os.Exit(1)
```suggestion
  log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +				os.Exit(1)
```suggestion
  log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +				os.Exit(1)
```suggestion
  log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
  log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +				os.Exit(1)
```suggestion
                              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +				os.Exit(1)
```suggestion
                              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +				os.Exit(1)
```suggestion
                              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
		log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
                     log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
                     log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
                     log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
                     log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
             log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
             log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
              log.Fatal(err)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
                      log.Fatalf("could not get home directory for data dir creation: %s", err.Error())
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
Rogue panic!!

```suggestion
                      log.Fatalf("invalid ID: %s in network identifier in %s file", chain.ID, GlobalConfig.PocketConfig.ChainsName)
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		fmt.Println(err)
Should likely stop execution or it will panic on the return statement
```suggestion
		log.Fatal(err)
```

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
		log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
		log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
		log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +		os.Exit(1)
```suggestion
		log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
		        log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
		        log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
		        log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
		        log.Fatal(NewInvalidChainsError(err))
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatal(err)

```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
		        log.Fatal("you must have a validator account password")
```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatal("validator address not set! please run set-validator")

```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatalf("expected level key to be first, got %v", keyvals[0])

```
stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatalf("canot open/create config json file: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatalf("cannot marshal default config into json: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatalf("cannot write default config to json file: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatalf("cannot marshal default config into json: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-12 17:59 UTC, edjroz commented on app/config.go
> +			os.Exit(1)
```suggestion
			log.Fatalf("cannot marshal default config into json: %s", err.Error())
```

stdlib package `log` offers `log.Fatalf` which logs the error with a timestamp & calls onto os.Exit(1)

the `log` package needs to also be added on this file for this suggestion to work

2020-05-13 17:06 UTC, merged